# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iChat
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'Firebase/Performance'
  pod 'Firebase/Database'

  target 'iChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iChatUITests' do
    # Pods for testing
  end

end
